server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    hikari:
      driverClassName: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
