spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.example.connect_databasetutorial
